import type { InvoiceLayoutField, InvoiceLayoutVariable } from '@shared/types/invoice-layout'

export const INVOICE_PAGE_WIDTH = 595
export const INVOICE_PAGE_HEIGHT = 842
export const INVOICE_DEFAULT_MARGIN = 50

export const INVOICE_LAYOUT_VARIABLES: InvoiceLayoutVariable[] = [
  { key: 'company.name', label: 'Company name', group: 'Company', sample: 'My Shop' },
  { key: 'company.address', label: 'Company address', group: 'Company', sample: '123 Market Road' },
  { key: 'company.phone', label: 'Company phone', group: 'Company', sample: '+91 98765 43210' },
  { key: 'company.gstin', label: 'Company GSTIN', group: 'Company', sample: '22AAAAA0000A1Z5' },
  { key: 'invoice.title', label: 'Invoice title', group: 'Invoice', sample: 'TAX INVOICE' },
  { key: 'invoice.number', label: 'Invoice number', group: 'Invoice', sample: 'INV-2026-001' },
  { key: 'invoice.date', label: 'Invoice date', group: 'Invoice', sample: '05/07/2026' },
  { key: 'order.number', label: 'Order number', group: 'Order', sample: 'ORD-1042' },
  { key: 'order.type', label: 'Order type', group: 'Order', sample: 'retail' },
  { key: 'customer.name', label: 'Customer name', group: 'Customer', sample: 'Rahul Sharma' },
  { key: 'customer.address', label: 'Customer address', group: 'Customer', sample: '45 Park Street' },
  { key: 'customer.phone', label: 'Customer phone', group: 'Customer', sample: '919876543210' },
  { key: 'customer.gstin', label: 'Customer GSTIN', group: 'Customer', sample: '29BBBBB1111B1Z6' },
  { key: 'order.notes', label: 'Order notes', group: 'Other', sample: 'Thank you for your business.' },
  { key: 'footer.text', label: 'Footer text', group: 'Other', sample: 'Generated by ShopFlow' }
]

function field(partial: InvoiceLayoutField): InvoiceLayoutField {
  return partial
}

export const DEFAULT_INVOICE_LAYOUT_FIELDS: InvoiceLayoutField[] = [
  field({
    id: 'company-name',
    type: 'variable',
    label: 'Company name',
    content: 'company.name',
    x: 50,
    y: 36,
    width: 495,
    height: 28,
    fontSize: 18,
    fontWeight: 'bold',
    align: 'center',
    visible: true
  }),
  field({
    id: 'invoice-title',
    type: 'variable',
    label: 'Title',
    content: 'invoice.title',
    x: 50,
    y: 68,
    width: 495,
    height: 20,
    fontSize: 12,
    fontWeight: 'bold',
    align: 'center',
    visible: true
  }),
  field({
    id: 'company-address',
    type: 'variable',
    label: 'Company address',
    content: 'company.address',
    x: 50,
    y: 92,
    width: 495,
    height: 16,
    fontSize: 10,
    fontWeight: 'normal',
    align: 'center',
    visible: true
  }),
  field({
    id: 'company-phone',
    type: 'variable',
    label: 'Company phone',
    content: 'company.phone',
    x: 50,
    y: 110,
    width: 495,
    height: 16,
    fontSize: 10,
    fontWeight: 'normal',
    align: 'center',
    visible: true
  }),
  field({
    id: 'invoice-meta',
    type: 'text',
    label: 'Invoice meta',
    content: 'Invoice No: {invoice.number}\nOrder No: {order.number}\nDate: {invoice.date}\nType: {order.type}',
    x: 50,
    y: 150,
    width: 240,
    height: 72,
    fontSize: 10,
    fontWeight: 'normal',
    align: 'left',
    visible: true
  }),
  field({
    id: 'bill-to',
    type: 'text',
    label: 'Bill to',
    content: 'Bill To\n{customer.name}\n{customer.address}\nPhone: {customer.phone}',
    x: 305,
    y: 150,
    width: 240,
    height: 88,
    fontSize: 10,
    fontWeight: 'normal',
    align: 'left',
    visible: true
  }),
  field({
    id: 'line-items',
    type: 'line_items',
    label: 'Line items',
    content: '',
    x: 50,
    y: 250,
    width: 495,
    height: 260,
    fontSize: 10,
    fontWeight: 'normal',
    align: 'left',
    visible: true
  }),
  field({
    id: 'totals',
    type: 'totals',
    label: 'Totals',
    content: '',
    x: 280,
    y: 530,
    width: 265,
    height: 120,
    fontSize: 10,
    fontWeight: 'normal',
    align: 'right',
    visible: true
  }),
  field({
    id: 'notes',
    type: 'variable',
    label: 'Notes',
    content: 'order.notes',
    x: 50,
    y: 670,
    width: 495,
    height: 48,
    fontSize: 10,
    fontWeight: 'normal',
    align: 'left',
    visible: true
  }),
  field({
    id: 'footer',
    type: 'variable',
    label: 'Footer',
    content: 'footer.text',
    x: 50,
    y: 790,
    width: 495,
    height: 16,
    fontSize: 9,
    fontWeight: 'normal',
    align: 'center',
    visible: true
  })
]

export const DEFAULT_INVOICE_LAYOUT_SEED = {
  name: 'Standard A4',
  description: 'Default ShopFlow invoice with header, bill-to, items table, and totals.',
  billTypes: ['simple', 'gst'] as const,
  isDefault: true,
  pageWidth: INVOICE_PAGE_WIDTH,
  pageHeight: INVOICE_PAGE_HEIGHT,
  margin: INVOICE_DEFAULT_MARGIN,
  fields: DEFAULT_INVOICE_LAYOUT_FIELDS
}
