import type { BillType, Order } from '@shared/types/order'
import type { CompanyProfile } from '@shared/types/company'
import type { Customer } from '@shared/types/customer'

function resolveCustomerAddress(order: Order, customer: Customer | null): string {
  const deliveryAddress = order.delivery?.address?.trim()
  if (deliveryAddress) return deliveryAddress
  return customer?.address?.trim() ?? ''
}

function resolveExtraCharges(order: Order): number {
  const fromTotals = order.totals.deliveryCharge ?? 0
  const fromDelivery = order.delivery?.charge ?? 0
  return Math.max(fromTotals, fromDelivery)
}

export function buildInvoiceVariableMap(options: {
  order: Order
  company: CompanyProfile
  customer: Customer | null
  billType: BillType
  invoiceNo: string
}): Record<string, string> {
  const { order, company, customer, billType, invoiceNo } = options
  const extraCharges = resolveExtraCharges(order)

  return {
    'company.name': company.name || 'ShopFlow',
    'company.address': company.address?.trim() ?? '',
    'company.phone': company.phone?.trim() ?? '',
    'company.gstin': company.gstin?.trim() ?? '',
    'invoice.title': billType === 'gst' ? 'TAX INVOICE' : 'BILL / INVOICE',
    'invoice.number': invoiceNo,
    'invoice.date': new Date().toLocaleDateString('en-IN'),
    'order.number': order.orderNo,
    'order.type': order.type,
    'customer.name': order.customerName || 'Walk-in Customer',
    'customer.address': resolveCustomerAddress(order, customer),
    'customer.phone': customer?.phone?.trim() ?? '',
    'customer.gstin': customer?.gstin?.trim() ?? '',
    'order.notes': order.notes?.trim() ?? '',
    'footer.text': 'Generated by ShopFlow',
    'totals.subtotal': String(order.totals.subtotal),
    'totals.discount': String(order.totals.discount),
    'totals.tax': String(order.totals.tax),
    'totals.extra': String(extraCharges),
    'totals.grand': String(order.totals.grandTotal)
  }
}

export function renderLayoutText(template: string, variables: Record<string, string>): string {
  return template.replace(/\{([a-z0-9._]+)\}/gi, (_match, key: string) => variables[key] ?? '')
}

export function resolveLayoutVariable(key: string, variables: Record<string, string>): string {
  return variables[key]?.trim() ?? ''
}
